export const data = [
  {
    img: "https://upload.wikimedia.org/wikipedia/en/9/99/Dangal_Poster.jpg",
    Name: "Dangal",
    Year: "2016",
    Cast: "Aamer Khan",
    cat: "inspiring",
    buy: "500rs",
  },
  {
    img: "https://i.ytimg.com/vi/vB2m1uRF30c/maxresdefault.jpg",
    Name: "Suryavanshi",
    Year: "1999",
    Cast: "Amitabh Bacchan",
    cat: "Family",
    buy: "10rs",
  },
  {
    img: "https://upload.wikimedia.org/wikipedia/en/1/1f/Sultan_film_poster.jpg",
    Name: "Sultan",
    Year: "2016",
    Cast: "Salman Khan",
    cat: "inspiring",
    buy: "220rs",
  },
  {
    img: "https://upload.wikimedia.org/wikipedia/en/thumb/e/e6/Zero_official_poster.jpg/220px-Zero_official_poster.jpg",
    Name: "Zero",
    Year: "2018",
    Cast: "SRK",
    cat: "Romance",
    buy: "50rs",
  },
  {
    img: "https://upload.wikimedia.org/wikipedia/en/d/df/3_idiots_poster.jpg",
    Name: "3 idiet",
    Year: "2007",
    Cast: "Aamer Khan",
    cat: "inspiring",
    buy: "1500rs",
  },
  {
    img: "https://m.media-amazon.com/images/M/MV5BMTczOTYwODAyNV5BMl5BanBnXkFtZTcwNTU2MjQ5Ng@@._V1_.jpg",
    Name: "Force",
    Year: "2011",
    Cast: "Jhon Ibrahim",
    cat: "Action",
    buy: "150rs",
  },
  {
    img: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRuNeY12sYTdIOmWvCvt55rap2rhxueuMtrKNwqpj9JHBB6Rgc_",
    Name: "Raees",
    Year: "2017",
    Cast: "SRK",
    cat: "Action",
    buy: "100rs",
  },
  {
    img: "https://static.toiimg.com/photo/45296934.cms",
    Name: "DDLJ",
    Year: "1995",
    Cast: "SRK",
    cat: "Romance",
    buy: "500px",
  },
];
